<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TouristPlacesSeeder extends Seeder
{
    public function run(): void
    {
        $places = [
            [
                'name'          => 'City Palace',
                'description'   => 'A magnificent palace complex at the heart of Jaipur, home to the royal family of Jaipur. It houses museums, courtyards, gardens and royal apartments with stunning Rajput and Mughal architecture.',
                'location'      => 'Jaipur, Rajasthan',
                'category'      => 'Heritage',
                'image'         => 'https://images.unsplash.com/photo-1599661046289-e31897851d41?q=80&w=1000&auto=format&fit=crop',
                'crowd_level'   => 85,
                'rating'        => 4.80,
                'entry_fee'     => 500.00,
                'opening_hours' => json_encode(['open' => '09:30', 'close' => '17:00']),
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'name'          => 'Amber Fort',
                'description'   => 'A majestic fort situated on the Aravalli Hills, known for its artistic Hindu style elements. The fort features stunning mirror work and intricate carvings. Elephants rides are available to the main gate.',
                'location'      => 'Amer, Rajasthan',
                'category'      => 'Fort',
                'image'         => 'https://images.unsplash.com/photo-1590050752117-23a97b62b423?q=80&w=1000&auto=format&fit=crop',
                'crowd_level'   => 65,
                'rating'        => 4.90,
                'entry_fee'     => 200.00,
                'opening_hours' => json_encode(['open' => '08:00', 'close' => '17:30']),
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'name'          => 'Hawa Mahal',
                'description'   => 'The iconic Palace of Winds, an extraordinary five-storey pyramid-shaped palace with 953 small windows (jharokhas) decorated with intricate latticework. Built in 1799 for royal ladies to observe street festivals.',
                'location'      => 'Jaipur, Rajasthan',
                'category'      => 'Landmark',
                'image'         => 'https://images.unsplash.com/photo-1603262110263-fb0110e71329?q=80&w=1000&auto=format&fit=crop',
                'crowd_level'   => 45,
                'rating'        => 4.70,
                'entry_fee'     => 50.00,
                'opening_hours' => json_encode(['open' => '09:00', 'close' => '16:30']),
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'name'          => 'Nahargarh Fort',
                'description'   => 'Perched on the edge of the Aravalli hills, Nahargarh Fort offers the most breathtaking panoramic views of Jaipur city. The fort is less crowded than Amber and ideal for sunrise photography.',
                'location'      => 'Jaipur, Rajasthan',
                'category'      => 'Fort',
                'image'         => 'https://images.unsplash.com/photo-1570168007204-dfb528c6958f?q=80&w=1000&auto=format&fit=crop',
                'crowd_level'   => 30,
                'rating'        => 4.60,
                'entry_fee'     => 50.00,
                'opening_hours' => json_encode(['open' => '10:00', 'close' => '17:30']),
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'name'          => 'Jantar Mantar',
                'description'   => 'A UNESCO World Heritage Site, Jantar Mantar is the largest stone observatory in the world built by Maharaja Sawai Jai Singh II in 1734. It features 19 giant astronomical instruments.',
                'location'      => 'Jaipur, Rajasthan',
                'category'      => 'Observatory',
                'image'         => 'https://images.unsplash.com/photo-1588528402605-1f1e2e0bf7c3?q=80&w=1000&auto=format&fit=crop',
                'crowd_level'   => 22,
                'rating'        => 4.50,
                'entry_fee'     => 200.00,
                'opening_hours' => json_encode(['open' => '09:00', 'close' => '16:30']),
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'name'          => 'Jal Mahal',
                'description'   => 'The Water Palace is a palace located in the middle of Man Sagar Lake. Surrounded by the Nahargarh hills, it is best visited at dusk when the golden hour light creates stunning reflections in the water.',
                'location'      => 'Jaipur, Rajasthan',
                'category'      => 'Landmark',
                'image'         => 'https://images.unsplash.com/photo-1625731226975-41c52e01f74f?q=80&w=1000&auto=format&fit=crop',
                'crowd_level'   => 55,
                'rating'        => 4.75,
                'entry_fee'     => 0.00,
                'opening_hours' => json_encode(['open' => '06:00', 'close' => '20:00']),
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'name'          => 'Albert Hall Museum',
                'description'   => 'The oldest museum in Rajasthan, located in Ram Niwas Garden. The museum houses an impressive collection of artifacts, paintings, jewellery, carpets, ivory, stone, metal sculptures and crystal works.',
                'location'      => 'Jaipur, Rajasthan',
                'category'      => 'Heritage',
                'image'         => 'https://images.unsplash.com/photo-1580130393679-e37c6ea95a40?q=80&w=1000&auto=format&fit=crop',
                'crowd_level'   => 25,
                'rating'        => 4.40,
                'entry_fee'     => 150.00,
                'opening_hours' => json_encode(['open' => '09:00', 'close' => '17:00']),
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'name'          => 'Birla Mandir',
                'description'   => 'A stunning white marble temple built by the Birla family in 1988. Dedicated to Lord Vishnu and Goddess Lakshmi, the temple is a peaceful spiritual retreat with beautiful carvings on its exterior walls.',
                'location'      => 'Jaipur, Rajasthan',
                'category'      => 'Nature',
                'image'         => 'https://images.unsplash.com/photo-1564507592333-c60657eea523?q=80&w=1000&auto=format&fit=crop',
                'crowd_level'   => 40,
                'rating'        => 4.55,
                'entry_fee'     => 0.00,
                'opening_hours' => json_encode(['open' => '06:00', 'close' => '12:00', 'afternoon_open' => '15:00', 'close_evening' => '21:00']),
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'name'          => 'Galtaji Temple',
                'description'   => 'Known as the Monkey Temple, Galtaji is a beautiful ancient pilgrimage site built into a narrow crevice in the ring of hills surrounding Jaipur. Natural fresh water springs fill the sacred kunds (pools).',
                'location'      => 'Jaipur, Rajasthan',
                'category'      => 'Nature',
                'image'         => 'https://images.unsplash.com/photo-1568558739564-0e53e7a50038?q=80&w=1000&auto=format&fit=crop',
                'crowd_level'   => 20,
                'rating'        => 4.30,
                'entry_fee'     => 0.00,
                'opening_hours' => json_encode(['open' => '05:00', 'close' => '20:00']),
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'name'          => 'Sisodia Rani Garden',
                'description'   => 'A beautiful terraced garden built by Maharaja Sawai Jai Singh II for his second queen. The garden features painted murals depicting tales of Radha-Krishna, fountains, pavilions and multi-level landscaping.',
                'location'      => 'Jaipur, Rajasthan',
                'category'      => 'Nature',
                'image'         => 'https://images.unsplash.com/photo-1587909209111-5097e18f42c1?q=80&w=1000&auto=format&fit=crop',
                'crowd_level'   => 15,
                'rating'        => 4.20,
                'entry_fee'     => 50.00,
                'opening_hours' => json_encode(['open' => '08:00', 'close' => '17:00']),
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'name'          => 'Jaigarh Fort',
                'description'   => 'Perched high on the Cheel ka Teela hill, Jaigarh Fort houses the world\'s largest cannon on wheels — the Jaivana. Connected to Amber Fort by an underground passage, it offers spectacular valley views.',
                'location'      => 'Jaipur, Rajasthan',
                'category'      => 'Fort',
                'image'         => 'https://images.unsplash.com/photo-1592298546438-9f644c83c827?q=80&w=1000&auto=format&fit=crop',
                'crowd_level'   => 35,
                'rating'        => 4.50,
                'entry_fee'     => 100.00,
                'opening_hours' => json_encode(['open' => '09:00', 'close' => '17:00']),
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'name'          => 'Johari Bazaar',
                'description'   => 'The jewellery market of Jaipur and the heart of the walled Pink City. Johari Bazar is famous for its dazzling gems, precious stones and traditional Rajasthani jewellery. Also a great spot for street food.',
                'location'      => 'Jaipur, Rajasthan',
                'category'      => 'Landmark',
                'image'         => 'https://images.unsplash.com/photo-1596522354195-e84ae3c98731?q=80&w=1000&auto=format&fit=crop',
                'crowd_level'   => 90,
                'rating'        => 4.35,
                'entry_fee'     => 0.00,
                'opening_hours' => json_encode(['open' => '10:00', 'close' => '20:00']),
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
        ];

        DB::table('tourist_places')->insert($places);
    }
}
